name: Weekly Stock Strategy

on:
  schedule:
    - cron: '0 1 * * 1'  # Every Monday at 01:00 UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  run-strategy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install yfinance pandas numpy ta requests

    - name: Run strategy
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python strategy.py